### ISSUE TITLE
Pass URLs in as a parameter

### ISSUE THREAD

**Issue by AlasdairGray** [jathanasiou/hw-dissertation-validata2#3]
Can we use parameterised URLs like the following to start the app and pull in the URL in the argument
http://www.macs.hw.ac.uk/SWeL/BioschemasValidator?url=https%3A%2F%2Fwww.guidetopharmacology.org%2Fcoronavirus.jsp?

**Comment by jathanasiou** [comment]
This should be possible now, but let me know here if there are any issues.
